### PR TITLE
Add multiple ci workflows

### PR DESCRIPTION
**Pull request by Hallis1221**
This PR adds CI for compiling the addon, spellchecking and translating issues that are not in englush

### CODE REVIEW

**Comment by Hallis1221** [comment]
@JaylyDev mind taking a look at this one?

**Comment by JaylyDev** [comment]
interesting workflow, but i don't really get why we get a translation from github issues

**Comment by Hallis1221** [comment]
> interesting workflow, but i don't really get why we get a translation from github issues

Seeing as issues is the main way players suggest new features translations can increase general communication abilities / lower the barrier to entry

**Comment by skybird23333** [comment]
> > interesting workflow, but i don't really get why we get a translation from github issues
> 
> Seeing as issues is the main way players suggest new features translations can increase general communication abilities / lower the barrier to entry

Discussion is the Github recommended way of suggestions rather than issues, and that should be enforced instead.

**Pull request merged**
